export const termsOfService = `
<div class="legal-document">
    <h1>Terms of Service</h1>
    <p class="last-updated">Last Updated: February 14, 2025</p>
    <p class="intro">PLEASE READ THESE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING THE SERVICE, YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS DESCRIBED HEREIN AND ALL TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE SERVICE.</p>

    <section>
        <h2>1. PREAMBLE AND DEFINITIONS</h2>
        <h3>1.1 Agreement to Terms</h3>
        <p>These Terms of Service (the "Terms") constitute a legally binding agreement between you, whether personally or on behalf of an entity ("User", "You", or "Your") and Quillix Intelligence Inc., a Delaware corporation ("Company", "We", "Us", or "Our"), concerning your access to and use of the website located at quillixai.com as well as any other media form, media channel, mobile website, or mobile application related, linked, or otherwise connected thereto (collectively, the "Platform").</p>
        
        <h3>1.2 Definitions</h3>
        <p>For the purposes of these Terms:</p>
        <ul>
            <li><strong>"Service"</strong> refers to the AI reasoning engine, chat interface, API, and all related services provided by Quillix.</li>
            <li><strong>"Content"</strong> means any text, graphics, images, audio, video, software, data compilations, and any other form of information capable of being stored in a computer that appears on or forms part of the Service.</li>
            <li><strong>"User Content"</strong> means any content submitted, posted, uploaded, published, or transmitted by users of the Service, including but not limited to chat inputs, uploaded files, and persona configurations.</li>
            <li><strong>"AI Output"</strong> means any text, image, code, or other data generated by the Service in response to User Content.</li>
        </ul>
    </section>

    <section>
        <h2>2. INTELLECTUAL PROPERTY RIGHTS</h2>
        <h3>2.1 Ownership of Service</h3>
        <p>Unless otherwise indicated, the Platform is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Platform (collectively, the "Platform Content") and the trademarks, service marks, and logos contained therein (the "Marks") are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, foreign jurisdictions, and international conventions.</p>
        
        <h3>2.2 Ownership of User Content</h3>
        <p>You retain all ownership rights to the User Content you upload or input into the Service. However, by inputting User Content, you grant the Company a non-exclusive, worldwide, royalty-free, fully paid-up, transferable, sublicensable, perpetual, and irrevocable license to copy, display, upload, perform, distribute, store, modify, and otherwise use your User Content solely for the purpose of providing, improving, and developing the Service.</p>
        
        <h3>2.3 Assignment of AI Output</h3>
        <p>Subject to your compliance with these Terms, Quillix Intelligence Inc. hereby assigns to you all its right, title, and interest in and to the AI Output generated by the Service in response to your User Content. You recognize that AI Output is generated by probabilistic algorithms and may not be unique to you.</p>
    </section>

    <section>
        <h2>3. USER REPRESENTATIONS AND WARRANTIES</h2>
        <p>By using the Platform, you represent and warrant that:</p>
        <ol>
            <li>All registration information you submit will be true, accurate, current, and complete.</li>
            <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
            <li>You have the legal capacity and you agree to comply with these Terms.</li>
            <li>You are not a minor in the jurisdiction in which you reside, or if a minor, you have received parental permission to use the Platform.</li>
            <li>You will not access the Platform through automated or non-human means, whether through a bot, script, or otherwise, except via official APIs provided by us.</li>
            <li>You will not use the Platform for any illegal or unauthorized purpose.</li>
            <li>Your use of the Platform will not violate any applicable law or regulation.</li>
        </ol>
    </section>

    <section>
        <h2>4. PROHIBITED ACTIVITIES</h2>
        <p>You may not access or use the Platform for any purpose other than that for which we make the Platform available. The Platform may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. Prohibited activities include, but are not limited to:</p>
        <ul>
            <li>Systematically retrieving data or other content from the Platform to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
            <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
            <li>Circumvent, disable, or otherwise interfere with security-related features of the Platform, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Platform and/or the Content contained therein.</li>
            <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Platform.</li>
            <li>Use any information obtained from the Platform in order to harass, abuse, or harm another person.</li>
            <li>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
            <li>Use the Platform in a manner inconsistent with any applicable laws or regulations.</li>
            <li>Engage in unauthorized framing of or linking to the Platform.</li>
            <li>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Platform or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Platform.</li>
            <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
            <li>Delete the copyright or other proprietary rights notice from any Content.</li>
            <li>Attempt to impersonate another user or person or use the username of another user.</li>
            <li>Sell or otherwise transfer your profile.</li>
            <li>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1x1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as "spyware" or "passive collection mechanisms" or "pcms").</li>
            <li>Interfere with, disrupt, or create an undue burden on the Platform or the networks or services connected to the Platform.</li>
            <li>Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Platform to you.</li>
            <li>Attempt to bypass any measures of the Platform designed to prevent or restrict access to the Platform, or any portion of the Platform.</li>
            <li>Copy or adapt the Platform’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
            <li>Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Platform.</li>
            <li>Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Platform, or using or launching any unauthorized script or other software.</li>
            <li>Use a buying agent or purchasing agent to make purchases on the Platform.</li>
            <li>Make any unauthorized use of the Platform, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
            <li>Use the Platform as part of any effort to compete with us or otherwise use the Platform and/or the Content for any revenue-generating endeavor or commercial enterprise.</li>
        </ul>
    </section>

    <section>
        <h2>5. SERVICE AVAILABILITY AND MODIFICATIONS</h2>
        <h3>5.1 Service Uptime</h3>
        <p>We cannot guarantee the Platform will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Platform, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Platform at any time or for any reason without notice to you.</p>
        
        <h3>5.2 No Liability for Downtime</h3>
        <p>You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Platform during any downtime or discontinuance of the Platform. Nothing in these Terms will be construed to obligate us to maintain and support the Platform or to supply any corrections, updates, or releases in connection therewith.</p>
    </section>

    <section>
        <h2>6. TERM AND TERMINATION</h2>
        <p>These Terms shall remain in full force and effect while you use the Platform. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE PLATFORM (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE PLATFORM OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</p>
        <p>If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
    </section>

    <section>
        <h2>7. DISCLAIMER</h2>
        <p>THE PLATFORM IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE PLATFORM AND OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE PLATFORM AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE PLATFORM’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE PLATFORM AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE PLATFORM, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE PLATFORM, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE PLATFORM BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PLATFORM. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE PLATFORM, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>
    </section>

    <section>
        <h2>8. LIMITATION OF LIABILITY</h2>
        <p>IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE PLATFORM, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE LESSER OF THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE SIX (6) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING OR $100.00 USD. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
    </section>

    <section>
        <h2>9. INDEMNIFICATION</h2>
        <p>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) your User Content; (2) use of the Platform; (3) breach of these Terms of Service; (4) any breach of your representations and warranties set forth in these Terms of Service; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Platform with whom you connected via the Platform. Use of the Platform to generate harmful, illegal, or infringing content is strictly prohibited, and you agree to indemnify us fully for any such use. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>
    </section>

    <section>
        <h2>10. USER DATA AND PRIVACY</h2>
        <p>We care about data privacy and security. Please review our Privacy Policy. By using the Platform, you agree to be bound by our Privacy Policy, which is incorporated into these Terms of Service. Please be advised the Platform is hosted in the United States. If you access the Platform from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in the United States, then through your continued use of the Platform, you are transferring your data to the United States, and you agree to have your data transferred to and processed in the United States.</p>
    </section>

    <section>
        <h2>11. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</h2>
        <p>Visiting the Platform, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Platform, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE PLATFORM. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</p>
    </section>

    <section>
        <h2>12. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
        <h3>12.1 Governing Law</h3>
        <p>These Terms shall be governed by and defined following the laws of the State of Delaware. Quillix Intelligence Inc. and yourself irrevocably consent that the courts of Delaware shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.</p>
        
        <h3>12.2 Binding Arbitration</h3>
        <p>Any dispute arising out of or in connection with this contract, including any question regarding its existence, validity, or termination, shall be referred to and finally resolved by the International Commercial Arbitration Court under the European Arbitration Chamber (Belgium, Brussels, Avenue Louise, 146) according to the Rules of this ICAC, which, as a result of referring to it, is considered as the part of this clause. The number of arbitrators shall be three (3). The seat, or legal place, of arbitration shall be Wilmington, Delaware. The language of the proceedings shall be English.</p>
        
        <h3>12.3 Class Action Waiver</h3>
        <p>Any arbitration under these Terms will take place on an individual basis; class arbitrations and class/representative/collective actions are not permitted. THE PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN EACH'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE AND/ OR REPRESENTATIVE PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL ACTION AGAINST THE OTHER.</p>
    </section>

    <section>
        <h2>13. MISCELLANEOUS</h2>
        <p>These Terms of Service and any policies or operating rules posted by us on the Platform or in respect to the Platform constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Service shall not operate as a waiver of such right or provision. These Terms of Service operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Terms of Service is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Service and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms of Service or use of the Platform. You agree that these Terms of Service will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Terms of Service and the lack of signing by the parties hereto to execute these Terms of Service.</p>
    </section>

    <section>
        <h2>14. CONTACT US</h2>
        <p>In order to resolve a complaint regarding the Platform or to receive further information regarding use of the Platform, please contact us at:</p>
        <p>Quillix Intelligence Inc.<br>
        Email: legal@quillixai.com</p>
    </section>
    
    <div style="height: 500px;"></div> <!-- Spacer to ensure scrollability and length perception -->
    <p class="end-marker">*** END OF TERMS OF SERVICE ***</p>
</div>
`;

export const privacyPolicy = `
<div class="legal-document">
    <h1>Privacy Policy</h1>
    <p class="last-updated">Last Updated: February 14, 2025</p>
    <p class="intro">Quillix Intelligence Inc. ("we," "us," or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website quillixai.com, including any other media form, media channel, mobile website, or mobile application related or connected thereto (collectively, the "Platform"). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.</p>

    <section>
        <h2>1. COLLECTION OF YOUR INFORMATION</h2>
        <p>We may collect information about you in a variety of ways. The information we may collect on the Platform includes:</p>
        
        <h3>1.1 Personal Data</h3>
        <p>Personally identifiable information, such as your name, shipping address, email address, and telephone number, and demographic information, such as your age, gender, hometown, and interests, that you voluntarily give to us when you register with the Platform or when you choose to participate in various activities related to the Platform, such as online chat and message boards. You are under no obligation to provide us with personal information of any kind, however your refusal to do so may prevent you from using certain features of the Platform.</p>
        
        <h3>1.2 Derivative Data</h3>
        <p>Information our servers automatically collect when you access the Platform, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the Platform.</p>
        
        <h3>1.3 Financial Data</h3>
        <p>Financial information, such as data related to your payment method (e.g., valid credit card number, card brand, expiration date) that we may collect when you purchase, order, return, exchange, or request information about our services from the Platform. We store only very limited, if any, financial information that we collect. Otherwise, all financial information is stored by our payment processor, Stripe, and you are encouraged to review their privacy policy and contact them directly for responses to your questions.</p>
        
        <h3>1.4 Mobile Device Data</h3>
        <p>Device information, such as your mobile device ID, model, and manufacturer, and information about the location of your device, if you access the Platform from a mobile device.</p>
        
        <h3>1.5 Third-Party Data</h3>
        <p>Information from third parties, such as personal information or network friends, if you connect your account to the third party and grant the Platform permission to access this information.</p>
        
        <h3>1.6 Data From Contests, Giveaways, and Surveys</h3>
        <p>Personal and other information you may provide when entering contests or giveaways and/or responding to surveys.</p>
    </section>

    <section>
        <h2>2. USE OF YOUR INFORMATION</h2>
        <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Platform to:</p>
        <ul>
            <li>Create and manage your account.</li>
            <li>Process your payments and refunds.</li>
            <li>Identify the user profile within our AI reasoning engine to provide personalized responses.</li>
            <li>Compile anonymous statistical data and analysis for use internally or with third parties.</li>
            <li>Deliver targeted advertising, coupons, newsletters, and other information regarding promotions and the Platform to you.</li>
            <li>Email you regarding your account or order.</li>
            <li>Enable user-to-user communications.</li>
            <li>Fulfill and manage purchases, orders, payments, and other transactions related to the Platform.</li>
            <li>Generate a personal profile about you to make future visits to the Platform more personalized.</li>
            <li>Increase the efficiency and operation of the Platform.</li>
            <li>Monitor and analyze usage and trends to improve your experience with the Platform.</li>
            <li>Notify you of updates to the Platform.</li>
            <li>Offer new products, services, and/or recommendations to you.</li>
            <li>Perform other business activities as needed.</li>
            <li>Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.</li>
            <li>Request feedback and contact you about your use of the Platform.</li>
            <li>Resolve disputes and troubleshoot problems.</li>
            <li>Respond to product and customer service requests.</li>
            <li>Send you a newsletter.</li>
            <li>Solicit support for the Platform.</li>
        </ul>
    </section>

    <section>
        <h2>3. DISCLOSURE OF YOUR INFORMATION</h2>
        <p>We may share information we have collected about you in certain situations. Your information may be disclosed as follows:</p>
        
        <h3>3.1 By Law or to Protect Rights</h3>
        <p>If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation. This includes exchanging information with other entities for fraud protection and credit risk reduction.</p>
        
        <h3>3.2 Third-Party Service Providers</h3>
        <p>We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance.</p>
        
        <h3>3.3 Marketing Communications</h3>
        <p>With your consent, or with an opportunity for you to withdraw consent, we may share your information with third parties for marketing purposes, as permitted by law.</p>
        
        <h3>3.4 Interactions with Other Users</h3>
        <p>If you interact with other users of the Platform, those users may see your name, profile photo, and descriptions of your activity, including sending invitations to other users, chatting with other users, liking posts, following blogs.</p>
        
        <h3>3.5 Online Postings</h3>
        <p>When you post comments, contributions or other content to the Platform, your posts may be viewed by all users and may be publicly distributed outside the Platform in perpetuity.</p>
        
        <h3>3.6 Third-Party Advertisers</h3>
        <p>We may use third-party advertising companies to serve ads when you visit the Platform. These companies may use information about your visits to the Platform and other websites that are contained in web cookies in order to provide advertisements about goods and services of interest to you.</p>
        
        <h3>3.7 Affiliates</h3>
        <p>We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</p>
        
        <h3>3.8 Business Partners</h3>
        <p>We may share your information with our business partners to offer you certain products, services or promotions.</p>
        
        <h3>3.9 Other Third Parties</h3>
        <p>We may share your information with advertisers and investors for the purpose of conducting general business analysis. We may also share your information with such third parties for marketing purposes, as permitted by law.</p>
        
        <h3>3.10 Sale or Bankruptcy</h3>
        <p>If we reorganize or sell all or a portion of our assets, undergo a merger, or are acquired by another entity, we may transfer your information to the successor entity. If we go out of business or enter bankruptcy, your information would be an asset transferred or acquired by a third party. You acknowledge that such transfers may occur and that the transferee may decline honor commitments we made in this Privacy Policy.</p>
    </section>

    <section>
        <h2>4. TRACKING TECHNOLOGIES</h2>
        <h3>4.1 Cookies and Web Beacons</h3>
        <p>We may use cookies, web beacons, tracking pixels, and other tracking technologies on the Platform to help customize the Platform and improve your experience. When you access the Platform, your personal information is not collected through the use of tracking technology. Most browsers are set to accept cookies by default. You can remove or reject cookies, but be aware that such action could affect the availability and functionality of the Platform. You may not decline web beacons. However, they can be rendered ineffective by declining all cookies or by modifying your web browser’s settings to notify you each time a cookie is tendered, permitting you to accept or decline cookies on an individual basis.</p>
        
        <h3>4.2 Internet-Based Advertising</h3>
        <p>Additionally, we may use third-party software to serve ads on the Platform, implement email marketing campaigns, and manage other interactive marketing initiatives. This third-party software may use cookies or similar tracking technology to help manage and optimize your online experience with us.</p>
        
        <h3>4.3 Website Analytics</h3>
        <p>We may also partner with selected third-party vendors, such as Google Analytics, to allow tracking technologies and remarketing services on the Platform through the use of first party cookies and third-party cookies, to, among other things, analyze and track users’ use of the Platform, determine the popularity of certain content and better understand online activity. By accessing the Platform, you consent to the collection and use of your information by these third-party vendors. You are encouraged to review their privacy policy and contact them directly for responses to your questions. We do not transfer personal information to these third-party vendors. However, if you do not want any information to be collected and used by tracking technologies, you can visit the third-party vendor or the Network Advertising Initiative Opt-Out Tool or Digital Advertising Alliance Opt-Out Tool.</p>
    </section>

    <section>
        <h2>5. THIRD-PARTY WEBSITES</h2>
        <p>The Platform may contain links to third-party websites and applications of interest, including advertisements and external services, that are not affiliated with us. Once you have used these links to leave the Platform, any information you provide to these third parties is not covered by this Privacy Policy, and we cannot guarantee the safety and privacy of your information. Before visiting and providing any information to any third-party websites, you should inform yourself of the privacy policies and practices (if any) of the third party responsible for that website, and should take those steps necessary to, in your discretion, protect the privacy of your information. We are not responsible for the content or privacy and security practices and policies of any third parties, including other sites, services or applications that may be linked to or from the Platform.</p>
    </section>

    <section>
        <h2>6. SECURITY OF YOUR INFORMATION</h2>
        <p>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse. Any information disclosed online is vulnerable to interception and misuse by unauthorized parties. Therefore, we cannot guarantee complete security if you provide personal information.</p>
    </section>

    <section>
        <h2>7. POLICY FOR CHILDREN</h2>
        <p>We do not knowingly solicit information from or market to children under the age of 13. If you become aware of any data we have collected from children under age 13, please contact us using the contact information provided below.</p>
    </section>

    <section>
        <h2>8. CONTROLS FOR DO-NOT-TRACK FEATURES</h2>
        <p>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ("DNT") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. No uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this Privacy Policy.</p>
    </section>

    <section>
        <h2>9. OPTIONS REGARDING YOUR INFORMATION</h2>
        <h3>9.1 Account Information</h3>
        <p>You may at any time review or change the information in your account or terminate your account by:</p>
        <ul>
            <li>Logging into your account settings and updating your account.</li>
            <li>Contacting us using the contact information provided below.</li>
        </ul>
        <p>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use and/or comply with legal requirements.</p>
        
        <h3>9.2 Emails and Communications</h3>
        <p>If you no longer wish to receive correspondence, emails, or other communications from us, you may opt-out by:</p>
        <ul>
            <li>Noting your preferences at the time you register your account with the Platform.</li>
            <li>Logging into your account settings and updating your preferences.</li>
            <li>Contacting us using the contact information provided below.</li>
        </ul>
        <p>If you no longer wish to receive correspondence, emails, or other communications from third parties, you are responsible for contacting the third party directly.</p>
    </section>

    <section>
        <h2>10. CALIFORNIA PRIVACY RIGHTS</h2>
        <p>California Civil Code Section 1798.83, also known as the "Shine The Light" law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</p>
        <p>If you are under 18 years of age, reside in California, and have a registered account with the Platform, you have the right to request removal of unwanted data that you publicly post on the Platform. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Platform, but please be aware that the data may not be completely or comprehensively removed from our systems.</p>
    </section>

    <section>
        <h2>11. GDPR COMPLIANCE (FOR EUROPEAN USERS)</h2>
        <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Quillix Intelligence Inc. aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
        <p>In certain circumstances, you have the following data protection rights:</p>
        <ul>
            <li><strong>The right to access, update or to delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
            <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
            <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
            <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
            <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
            <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where we relied on your consent to process your personal information.</li>
        </ul>
        <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
        <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
    </section>

    <section>
        <h2>12. CONTACT US</h2>
        <p>If you have questions or comments about this Privacy Policy, please contact us at:</p>
        <p>Quillix Intelligence Inc.<br>
        Email: privacy@quillixai.com</p>
    </section>
    
    <div style="height: 500px;"></div> <!-- Spacer to ensure scrollability and length perception -->
    <p class="end-marker">*** END OF PRIVACY POLICY ***</p>
</div>
`;