export const termsOfService = `
<div class="legal-document">
    <h1>Terms of Service</h1>
    <p class="last-updated">Last Updated: October 26, 2023</p>

    <section>
        <h2>1. PREAMBLE AND ACCEPTANCE OF TERMS</h2>
        <p>Welcome to Quillix ("we," "us," "our," or the "Service"), a proprietary artificial intelligence reasoning engine and platform operated by Quillix Intelligence Inc. By accessing, browsing, or using the Quillix website (quillixai.com), its subdomains, APIs, mobile applications, or any associated services (collectively, the "Platform"), you ("User," "you," or "your") acknowledge that you have read, understood, and agree to be bound by these Terms of Service ("Terms") and our Privacy Policy.</p>
        <p>IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST IMMEDIATELY DISCONTINUE USE OF THE SERVICE. THESE TERMS CONTAIN A MANDATORY ARBITRATION PROVISION AND CLASS ACTION WAIVER THAT AFFECT YOUR RIGHTS.</p>
    </section>

    <section>
        <h2>2. ELIGIBILITY AND ACCOUNT REGISTRATION</h2>
        <h3>2.1 Age Requirement</h3>
        <p>The Service is strictly intended for users who are at least 13 years of age. If you are under 18, you represent that you have your parent or guardian's permission to use the Service. Users under 13 are strictly prohibited from using the Service.</p>
        <h3>2.2 Account Security</h3>
        <p>You are responsible for maintaining the confidentiality of your login credentials. You agree to notify us immediately of any unauthorized access to or use of your account. Quillix Intelligence Inc. cannot and will not be liable for any loss or damage arising from your failure to comply with this security obligation.</p>
    </section>

    <section>
        <h2>3. USE OF THE ARTIFICIAL INTELLIGENCE ENGINE</h2>
        <h3>3.1 Experimental Nature</h3>
        <p>You acknowledge that Quillix is an experimental AI technology. Responses generated by the Service ("Output") are probabilistic and may be inaccurate, offensive, or inappropriate. You agree that you will not rely on the Output for professional advice, including but not limited to medical, legal, financial, or engineering advice.</p>
        <h3>3.2 Input Ownership</h3>
        <p>You retain all rights to the text, files, and data you upload or input into the Service ("Input"). By submitting Input, you grant Quillix Intelligence Inc. a worldwide, non-exclusive, royalty-free license to process, store, and use your Input solely for the purpose of providing and improving the Service.</p>
        <h3>3.3 Prohibited Uses</h3>
        <p>You agree not to use the Service to:</p>
        <ul>
            <li>Generate content that promotes violence, hate speech, self-harm, or illegal acts.</li>
            <li>Reverse engineer, decompile, or attempt to derive the source code or underlying models of the Service.</li>
            <li>Use the Output to develop a competing machine learning model or service.</li>
            <li>Automate access to the Service via "scraping," "crawling," or unauthorized API calls.</li>
        </ul>
    </section>

    <section>
        <h2>4. INTELLECTUAL PROPERTY RIGHTS</h2>
        <p>The Service, including its architecture, visual design, user interface, "Quillix" trademark, and proprietary code (including the reasoning engine algorithms), is the exclusive property of Quillix Intelligence Inc. and its licensors. Except for the limited license granted herein, no other rights are granted to you.</p>
    </section>

    <section>
        <h2>5. DISCLAIMER OF WARRANTIES</h2>
        <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, QUILLIX INTELLIGENCE INC. DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.</p>
    </section>

    <section>
        <h2>6. LIMITATION OF LIABILITY</h2>
        <p>IN NO EVENT SHALL QUILLIX INTELLIGENCE INC., ITS DIRECTORS, EMPLOYEES, PARTNERS, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY.</p>
    </section>

    <section>
        <h2>7. INDEMNIFICATION</h2>
        <p>You agree to indemnify, defend, and hold harmless Quillix Intelligence Inc. from any claims, damages, liabilities, costs, or expenses (including legal fees) arising from: (i) your use of the Service; (ii) your violation of these Terms; (iii) your violation of any third-party right, including intellectual property or privacy rights.</p>
    </section>

    <section>
        <h2>8. DISPUTE RESOLUTION AND ARBITRATION</h2>
        <p>Any dispute arising out of or relating to these Terms or the Service shall be resolved through binding arbitration conducted by the American Arbitration Association (AAA) in accordance with its Commercial Arbitration Rules. You agree to waive your right to a trial by jury and to participate in a class action lawsuit.</p>
    </section>

    <section>
        <h2>9. MODIFICATIONS TO TERMS</h2>
        <p>We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by posting the revised Terms on the Platform. Your continued use of the Service after the effective date of the revised Terms constitutes your acceptance of the changes.</p>
    </section>

    <section>
        <h2>10. TERMINATION</h2>
        <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.</p>
    </section>

    <section>
        <h2>11. GOVERNING LAW</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.</p>
    </section>

    <section>
        <h2>12. ENTIRE AGREEMENT</h2>
        <p>These Terms constitute the entire agreement between you and Quillix Intelligence Inc. regarding our Service and supersede and replace any prior agreements we might have had between us regarding the Service.</p>
    </section>
    
    <p class="end-marker">*** END OF TERMS OF SERVICE ***</p>
</div>
`;

export const privacyPolicy = `
<div class="legal-document">
    <h1>Privacy Policy</h1>
    <p class="last-updated">Last Updated: October 26, 2023</p>

    <section>
        <h2>1. INTRODUCTION</h2>
        <p>Quillix Intelligence Inc. ("we," "our," or "us") respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website quillixai.com and our AI reasoning services.</p>
    </section>

    <section>
        <h2>2. INFORMATION WE COLLECT</h2>
        <h3>2.1 Personal Information</h3>
        <p>We may collect personally identifiable information, such as your name, email address, and IP address, when you register for an account, subscribe to our newsletter, or contact us for support.</p>
        <h3>2.2 Usage Data</h3>
        <p>We automatically collect certain information when you access the Service, including your device type, browser version, operating system, unique device identifiers, and diagnostic data.</p>
        <h3>2.3 User Content</h3>
        <p>We collect the text, files, and other data you input into the Service ("Inputs") and the content generated by the Service ("Outputs"). We treat this data with strict confidentiality.</p>
    </section>

    <section>
        <h2>3. HOW WE USE YOUR INFORMATION</h2>
        <p>We use the information we collect for the following purposes:</p>
        <ul>
            <li>To provide, maintain, and improve the Service.</li>
            <li>To manage your account and authentication.</li>
            <li>To communicate with you about updates, security alerts, and support messages.</li>
            <li>To monitor and analyze trends, usage, and activities in connection with the Service.</li>
            <li>To detect, prevent, and address technical issues and fraud.</li>
        </ul>
    </section>

    <section>
        <h2>4. DATA STORAGE AND SECURITY</h2>
        <p>Your data is stored securely using enterprise-grade encryption standards. We utilize Supabase for database management, which implements rigorous security protocols. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
    </section>

    <section>
        <h2>5. SHARING OF INFORMATION</h2>
        <p>We do not sell your personal information. We may share your information with:</p>
        <ul>
            <li><strong>Service Providers:</strong> Third-party vendors who perform services on our behalf (e.g., hosting, analytics).</li>
            <li><strong>Legal Requirements:</strong> If required to do so by law or in response to valid requests by public authorities.</li>
            <li><strong>Business Transfers:</strong> In connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business.</li>
        </ul>
    </section>

    <section>
        <h2>6. YOUR DATA RIGHTS</h2>
        <p>Depending on your location, you may have the following rights regarding your data:</p>
        <ul>
            <li><strong>Access:</strong> The right to request copies of your personal data.</li>
            <li><strong>Rectification:</strong> The right to request that we correct any information you believe is inaccurate.</li>
            <li><strong>Erasure:</strong> The right to request that we erase your personal data ("Right to be Forgotten").</li>
            <li><strong>Portability:</strong> The right to request that we transfer the data that we have collected to another organization, or directly to you.</li>
        </ul>
    </section>

    <section>
        <h2>7. AI TRAINING AND IMPROVEMENT</h2>
        <p>We may use anonymized and aggregated User Content to improve our machine learning models. If you wish to opt-out of having your data used for model training, please contact our support team or adjust your account settings.</p>
    </section>

    <section>
        <h2>8. COOKIES AND TRACKING</h2>
        <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>
    </section>

    <section>
        <h2>9. CHILDREN'S PRIVACY</h2>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
    </section>

    <section>
        <h2>10. CHANGES TO THIS PRIVACY POLICY</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
    </section>

    <section>
        <h2>11. CONTACT US</h2>
        <p>If you have any questions about this Privacy Policy, please contact us via email at support@quillixai.com.</p>
    </section>

    <p class="end-marker">*** END OF PRIVACY POLICY ***</p>
</div>
`;